### ISSUE TITLE
How should we implement forceful close of async resources?

### ISSUE THREAD

**Issue by agronholm** [agronholm/anyio#131]
Sometimes we need to close connections and other async resources forcefully. To this end, trio has a function named `aclose_forcefully()` which creates a cancel scope and within it, cancels the scope and *then* calls `aclose()` on the resource.
My other idea is that we could add a parameter `force: bool = False` to the `AsyncResource.aclose()` interface.

Pros of `force`:

- Cleaner (?)
- The callee has better control over the procedure

Cons:

- Another divergence from the trio API
- Requires more care from the developer of the resource

**Comment by smurfix** [comment]
I don't like `force=True` because `aclose` must work correctly no matter whether it's cancelled or not, otherwise you'd leave the resource in an undetermined state. I.e. you need to implement (and test) the call-from-cancelled-scope method anyway.

Thus if you add that parameter you'd implement two ways to do essentially the same thing.
