### ISSUE TITLE
Should we implement an asyncio-like get_extra_info() method on streams?

### ISSUE THREAD

**Issue by agronholm** [agronholm/anyio#133]
We have stream wrappers such as `TLSStream` and `BufferedByteReceiveStream` which expose a different set of attributes than the streams they wrap. I imagine it will be quite inconvenient for developers that just want the remote address (for example) to manually traverse the chain of wrapped transports to find the information they want. Asyncio has a pretty convenient solution to this: [get_extra_info()](https://docs.python.org/3/library/asyncio-protocol.html?#asyncio.BaseTransport.get_extra_info). I think it would be really useful provide a similar method so developers don't have to care how many layers down the information resides.

**Comment by agronholm** [comment]
@njsmith pointed out that different stream layers may have overlapping property names with different semantics. This is not currently a showstopper issue, but something we need to be aware of. One workaround for that would be the ability to specify a stream class as a separate argument so that only the property value from a matching layer is returned.

**Comment by agronholm** [comment]
Maybe a simpler solution would be to prefix the properties, like `tls.compression` or `socket.peername` etc.? This is so that layers could intentionally override each other's values as necessary.

**Comment by njsmith** [comment]
My gut feeling is that automagic heuristics for blowing through abstraction layers like this tend to come back and bite you later.

**Comment by agronholm** [comment]
We always provide a way for developers to dig through the layers manually, but would you really suggest that we don't provide any shortcuts for that?

**Comment by agronholm** [comment]
A very common use case is when you have a TLS wrapped connection. The TLS stream class does not expose any socket specific information so the developer would have to go at least one layer down to find that info.

**Comment by njsmith** [comment]
> would you really suggest that we don't provide any shortcuts for that?

yeah, maybe? obviously if it turns out to be unbearable verbose then that's an issue we'd need to address, but I feel like if you want to mess around with TLS details then you're probably doing that in a layer that knows that it has a TLSStream object?

If you have a generic stream, then there might be a socket used exclusively for this stream, there might be a socket that's shared with other streams via some multiplexing protocol, there might be multiple sockets, there might be no socket at all. The whole point of abstract interfaces is that you don't know :-). OTOH if you know you have a specific layering, then you don't have an abstract interface; you can take advantage of the class-specific attributes.

As mentioned on gitter, I do think it makes sense to have best-effort "what's my address"/"what's the peer address" methods on the stream interface. Usually people just want these to like, shove them into logs or whatever on a best-effort basis, so it's OK if they're not always programmatically useful. Also, some important wrapper streams like the [PROXY protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) will actually want to override these. But the key thing is that it actually makes sense on any stream to say "hey, can you give me some vague clue about your peer address, if you have any", without breaking abstractions or making assumptions about the exact layering, because the contract is so weak.

**Comment by agronholm** [comment]
> yeah, maybe? obviously if it turns out to be unbearable verbose then that's an issue we'd need to address, but I feel like if you want to mess around with TLS details then you're probably doing that in a layer that knows that it has a TLSStream object?

Unless you add layers like compression, serialization and whatnot on top of that, at which point you'll have to go excavate the `TLSStream` from underneath those to get this information.

To sum this up, we have a couple practical use cases so far:

1. Get a generic "peer address" and "local address" from socket streams
2. Get TLS specific information like the peer certificate

Potential solutions:

1. Prefix the property names, like `tls.peer_certificate`
2. Require a stream class name as the second argument

The problem with solution 1 is that adding more down the line becomes an issue with SemVer because a user might have defined their own property with the same name. The prefixing mitigates but does not solve the problem.

Solution 2 is more verbose but much safer. Do you see obvious problems with that one?

**Comment by agronholm** [comment]
I managed to implement a scheme similar to asyncio's `get_extra_info()` but with singleton keys and type safety.

**Comment by agronholm** [comment]
It was pointed out on Gitter that classes exposing such attributes should have some way to enumerate the supported attributes, for debugging/monitoring purposes.
