### ISSUE TITLE
Documentation should point out that anyone looking for queues should use memory object streams

### ISSUE THREAD

**Issue by illuminatedwax** [agronholm/anyio#169]
Anyone looking to replace queues using the anyio library will be very confused when looking through the AnyIO documentation. A single sentence, like "similar to queues", would go a long way.

**Comment by agronholm** [comment]
Searching for "queue" will give this as a result: `Added memory object streams as a replacement for queues`. Is this not clear enough?

**Comment by illuminatedwax** [comment]
Speaking as someone who went through this, having this mentioned only in "Version History" took quite a while to find, and I only looked there because I guessed to Google search for "anyio create_queue" and found that it used to be in the API.

**Comment by agronholm** [comment]
I'm not sure that would be visible from a Google search either, but I'll make an effort.

**Comment by jakkdl** [comment]
I just went through the same thing - searching for "queue" in the docs only gave me 
![2023-11-10T13:09:07,096996727+01:00](https://github.com/agronholm/anyio/assets/11260241/8c8e9c6c-a125-45b9-ad6d-c6e2010a6698)
and since it doesn't say that there are more hits in the page I didn't bother clicking through to it. If you don't want to mention queues in the docs for `create_memory_object_stream` you could possibly add it in the FAQ.

**Comment by jakkdl** [comment]
oh actually, https://anyio.readthedocs.io/en/stable/streams.html#memory-object-streams mentions "queues" - but the search isn't smart enough to match to that :upside_down_face:
