### ISSUE TITLE
tasks that await a native asyncio.Future are not cancelled

### ISSUE THREAD

**Issue by graingert** [agronholm/anyio#199]
```python
import asyncio
import anyio

async def amain():
    async def foo():
        loop = asyncio.get_running_loop()
        await loop.create_future()

    async with anyio.create_task_group() as tg:
        await tg.spawn(foo)
        await tg.cancel_scope.cancel()

anyio.run(amain)  # never completes
```

**Comment by agronholm** [comment]
This is a tricky problem because asyncio tasks are deliberately not cancelled automatically when the cancel scope is cancelled, unless they're currently waiting on something. This is to match trio's semantics of allowing the task to react to the cancellation first. If only AnyIO code is used, this works fine because when it runs into a checkpoint, the task gets cancelled automatically. When it's native asyncio code, however, it won't work.
