### ISSUE TITLE
Add a way to use Locks with values

### ISSUE THREAD

**Issue by martmists-gh** [agronholm/anyio#36]
Asyncio has 
```py
fut = loop.create_future()
# spawn a task that will set fut
await fut
return fut.result()
```
AnyIO does not offer a way to set values on a Lock or similar, so having something like that would be really useful.

**Comment by agronholm** [comment]
AnyIO specifically did not add support for Futures since neither curio or trio supports such a notion. What is your use case?

**Comment by martmists** [comment]
My use case is to queue futures from the main execution while a worker processes each, which does not have to be in order due to receiving data from an external source. The main execution can decide to either wait or spawn a new task that waits for it, requiring the worker to set the value which is then used later on in the function. 

Currently, I use a `List[Dict[str, Union[Event, ReturnValue]]]` as queue instead, but being able to just use Events/Locks would be preferred.

**Comment by agronholm** [comment]
Why not just use a Queue?

**Comment by smurfix** [comment]
My current usecases for this data structure are
(a) an encapsulation of @martmists 's `Union[Event, ReturnValue]` structure in client/server applications
(b) as a parameter for spawning a new tasks which I later might want to cancel. Trio has a `task_status.started()` which I can use to return that to my caller; rather than passing in a bare `Event` and using some other place for the actual result, I tend to use some sort of `ValueEvent` class that acts like a Future.

So, I'd be in favor of putting something like this in `anyio.helper` (or find some other name for "nice-to-have stuff that's frequently used/required but not part of the core in any strict sense") module.

```
import attr
import outcome
from . import create_event, CancelledError

@attr.s
class ValueEvent:
    """A waitable value useful for inter-task synchronization,
    inspired by :class:`threading.Event`.

    An event object manages an internal value, which is initially
    unset, and tasks can wait for it to become True.

    """

    event = attr.ib(factory=create_event, init=False)
    value = attr.ib(default=None, init=False)

    async def set(self, value):
        """Set the internal flag value to True, and wake any waiting tasks.

        """
        self.value = outcome.Value(value)
        await self.event.set()

    def is_set(self):
        return self.value is not None

    async def set_error(self, exc):
        """Set the internal flag value to True, and wake any waiting tasks.

        """
        self.value = outcome.Error(exc)
        await self.event.set()

    def cancel(self):
        self.set_error(CancelledError)

    async def get(self):
        """Block until the internal flag value becomes True.

        If it's already True, then this method is still a checkpoint, but
        otherwise returns immediately.

        """
        await self.event.wait()
        return self.value.unwrap()
```

**Comment by agronholm** [comment]
This would not help to cancel the task though. If either of you can provide real code that shows your current workarounds, that would be helpful in determining the right approach here.

As far as the naming goes, the word `Promise` has been around in the ECMAScript world. Maybe use that?

**Comment by smurfix** [comment]
Well, if/when the central exits then of course it needs to tell all its clients. That can be done with another class on top that encapsulates the `Dict[str, ValueEvent]` and a context manager which sends an error to any requestor whose task is still open. That's easy to write. Shall I prepare a pull request?

WRT naming, `Promise` is good enough WRT the class's features, but the implementation / usage is wildly different. Worse, there already is a `promise` package on PyPi that behaves mostly like its JavaScript counterpart.

**Comment by agronholm** [comment]
So to summarize, `ValueEvent` would be an `Event` which cannot be reset and which carries an `Outcome`, yes?

**Comment by smurfix** [comment]
Correct.

**Comment by agronholm** [comment]
I have no problem with this. I'm just wondering why neither trio or curio have such a thing natively if it's so important?

**Comment by smurfix** [comment]
trio has an open issue for this. Point 1 is that it's so easy to code a simple Promise/ValueEvent/Future/whatever, so you can just do it yourself. The problem is that Trio prides itself on correctly solving problems, and a complete solution should support cancelling a single client, and then you need to tell the server that the result is no longer needed, and suddenly you're mired in a moat of implementation options which we don't have experience how to handle.

Point 2 is that `Future` objects, in asyncio, are used in a heap of usecases which are completely irrelevant/unnecessary in anyio/trio, so if we offer such a thing people are going to use them instead of thinking about how to solve their problem in a much more trio-idiomatic way.

If anyio implements something like this it should thus document that most traditional uses of `Future` are superseded by anyio's other mechanisms (particularly taskgroups), and the only applications we've so far discovered it's useful/necessary for are multiple-client/server patterns. Or maybe returning a single value when a long-running tasks have finished starting up.

**Comment by agronholm** [comment]
And this is why I wanted to see the actual code, to determine if this was necessary at all.

**Comment by martmists** [comment]
Here's an UMLS Diagram of my situation

![image](https://user-images.githubusercontent.com/16361449/48839183-e8b13f00-ed8a-11e8-94c7-195e07524ee8.png)

In this context, reader is a task:
```py
    async def _read_loop(self):
        while self._do_loop:
            # Read a single line
            # _sock: anyio.abc.SocketStream
            line = await self._sock.receive_until(b"\n", self._buf_size)
            data = json.loads(line.decode('utf-8'))

            event = data['event']
            built = self._build_event(data)

            if self._locks:
                for entry in self._locks:
                    if entry['function'](data):
                        self._locks.remove(entry)
                        entry["result"] = built
                        await entry['event'].set()
```
The current implementation for wait_for:
```py
    async def wait_for(self, event=None, command=None, type_: T = Event) -> T:
        if event is not None:
            f = lambda x: x['event'] == event or (event == "command" and "error" in x
                                                  and x['error'] == "Invalid command")
        elif command is not None:
            f = lambda x: x.get('cmd') == command
        else:
            f = lambda: True

        event = anyio.create_event()
        entry: Dict[str, Any] = {
            "function": f,
            "event": event,
            "result": None
        }

        self._locks.append(entry)
        await event.wait()

        assert isinstance(entry["result"], type_)

        return entry["result"]
```

**Comment by smurfix** [comment]
On further thought, the way forward is probably a `RequestManager` that properly supports bidirectional cancellation.  Not for 1.0, but I'll prepare a pull request for something like that, one of these days.

**Comment by agronholm** [comment]
I am not convinced that we should do this. Memory object streams, events or combinations thereof should suffice for most cases. I can reopen this when presented with a more convincing case in its favor.
