### ISSUE TITLE
Allow use of mixed asyncio/curio/trio

### ISSUE THREAD

**Issue by martmists** [agronholm/anyio#47]
Our project aims to allow the end user to write extensions in any of the async libraries provided by anyio, but it seems this is either undocumented or not yet possible. Please implement a way to make this work.

code used:

```py
import anyio, curio, trio

async def curio_coro():
    await curio.sleep(1)
    print("Hello from curio!")

async def trio_coro():
    await trio.sleep(1)
    print("Hello from trio!")

async def run_both():
    async with anyio.create_task_group() as tg:
        await tg.spawn(curio_coro)
        await tg.spawn(trio_coro)

anyio.run(run_both)
```

In this context, `curio_coro` and `trio_coro` would be functions written by our end users.

**Comment by smurfix** [comment]
This is not possible and IMHO out of scope of anyio.

You can run asyncio modules on top of trio, with the `trio_asyncio` module. There's no such thing for curio and I don't think anybody would want to do the (substantial) work to implement that, given tee fact that curio is a nice module.

**Comment by agronholm** [comment]
As @smurfix pointed out, this is impossible.

**Comment by smurfix** [comment]
Solution: tell your users to write your modules in any of trio, asyncio (with trio-asyncio helper) or anyio. If it's new code, I'd tell them "trio or anyio; if you need to use an asyncio-only library, use trio_asyncio". You need to structure your plugin so that they can run the trio-asyncio adapter in their own code.
