### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [agronholm/anyio#602]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

Is it possible next time on release new version make the github release to have entry on https://github.com/agronholm/anyio/releases? 🤔

More about gh releases is possible to find on
https://pgjones.dev/blog/trusted-plublishing-2023/
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release

### Use case

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

**Comment by agronholm** [comment]
Is it not possible for you to catch these from the [PyPI RSS stream](https://pypi.org/rss/project/anyio/releases.xml)? Not all projects use GitHub.

**Comment by kloczek** [comment]
Easiest way of adding GH release oof python modules is modify pypi release process
https://pgjones.dev/blog/trusted-plublishing-2023/

**Comment by agronholm** [comment]
> On pypi is registered +250K modules and github allow set watch->release on each chosen repo.

So what if there are 250k+ modules? The RSS link I pasted earlier is for AnyIO releases only.

I would recommend libraries.io but it seems they've long ago stopped allowing new subscriptions.

> Easiest way of adding GH release oof python modules is modify pypi release process

I already know how to make a GH release. The problem was extracting the relevant part of the changelog to be part of the release text (as users would expect there to be a list of changes), and I haven't seen any automation for that anywhere. It's certainly possible, but I haven't had time to do that yet as I've been busy working on the actual projects.
