### ISSUE TITLE
Release 1.1.1?

### ISSUE THREAD

**Issue by florimondmanca** [agronholm/anyio#80]
Hey,

Now that #74 has been resolved via #76, I was wondering what would be the release schedule for the next patch?

Besides, there seems to be [a couple of items](https://github.com/agronholm/anyio/compare/1.1.0...HEAD) waiting for release.

Let me know if I can give a helping hand on this.

**Comment by agronholm** [comment]
I'd appreciate if you asked such questions over Gitter on the trio channel instead of opening an issue.

To answer the question though, AnyIO follows semantic versioning so the next version is going to be 1.2.0 due to the introduction of new features. I will be working on #71 today and once it's been merged, I'm ready to make the new release.

**Comment by florimondmanca** [comment]
> I'd appreciate if you asked such questions over Gitter on the trio channel instead of opening an issue.

Oh, sure. I wasn't aware there anyio project members were active there.

> To answer the question though,

Thanks!
